# Generated by Django 5.1.4 on 2024-12-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='diagnostic',
            field=models.TextField(blank=True, verbose_name='Diagnostic'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='traitement',
            field=models.TextField(blank=True, verbose_name='Traitement'),
        ),
    ]
