# Generated by Django 5.1.4 on 2024-12-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_consultation_diagnostic_consultation_traitement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='phone',
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
