# Generated by Django 5.1.4 on 2024-12-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_doctor_license_number_remove_doctor_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='consultation',
            name='reference',
            field=models.CharField(default=0, editable=False, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='license_number',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone',
            field=models.CharField(default=3, max_length=15),
            preserve_default=False,
        ),
    ]
