# Generated by Django 5.1.4 on 2024-12-15 12:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_appointment_options_remove_appointment_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-date'], 'verbose_name': 'Rendez-vous', 'verbose_name_plural': 'Rendez-vous'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['user__last_name', 'user__first_name'], 'verbose_name': 'Médecin', 'verbose_name_plural': 'Médecins'},
        ),
        migrations.RenameField(
            model_name='consultation',
            old_name='diagnostic',
            new_name='diagnosis',
        ),
        migrations.AddField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='office_hours',
            field=models.TextField(blank=True, verbose_name='Horaires de consultation'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.patient'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.TextField(verbose_name='Motif'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmé'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='license_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Numéro de licence'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(choices=[('GENERAL', 'Médecine Générale'), ('CARDIO', 'Cardiologie'), ('DERMA', 'Dermatologie'), ('PEDIATRE', 'Pédiatrie'), ('OPHTALMO', 'Ophtalmologie'), ('GYNECO', 'Gynécologie'), ('ORTHO', 'Orthopédie'), ('NEURO', 'Neurologie'), ('PSYCHIATRE', 'Psychiatrie'), ('ORL', 'Oto-rhino-laryngologie'), ('GASTRO', 'Gastro-entérologie'), ('ENDOCRINO', 'Endocrinologie'), ('PNEUMO', 'Pneumologie'), ('NEPHRO', 'Néphrologie'), ('HEMATO', 'Hématologie'), ('RADIO', 'Radiologie'), ('URGENTISTE', "Médecine d'urgence"), ('CHIRURGIE', 'Chirurgie générale'), ('ANESTHESIE', 'Anesthésie-réanimation'), ('RHUMATO', 'Rhumatologie')], max_length=50, verbose_name='Spécialité'),
        ),
    ]
