# Generated by Django 5.1.4 on 2024-12-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_appointment_options_alter_doctor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='notes_medicales',
            field=models.TextField(blank=True, verbose_name='Notes médicales'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='recommandations',
            field=models.TextField(blank=True, verbose_name='Recommandations'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='symptoms',
            field=models.TextField(blank=True, default='', verbose_name='Symptômes'),
        ),
    ]
